version: '5'

services:
  db:
    image: postgres
  migration:
    build: .
    command:
    volumes:
      - .:/home/jim/Tjs/Hiw
    depends_on:
      - db
  web:
    build: .
    command:
    volumes:
    -